"""Dual-run pipeline for test_spark_merge_serverless_dag (generated by bh-migrate).

Trigger-based topology with Databricks serverless PySpark tasks, matching the
source DAG compute model.
"""

from __future__ import annotations

from datetime import datetime, timedelta

from airflow import DAG
from airflow.operators.trigger_dagrun import TriggerDagRunOperator
from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator

DATABRICKS_CONN_ID = "databricks_default"

default_args = {
    "owner": "data-platform",
    "depends_on_past": False,
    "retries": 0,
    "retry_delay": timedelta(minutes=5),
}

SOURCE_DAG_CONF = {
    "dual_run": {
        "mode": "source",
        "clone_index": 1,
        "main_class": "com.example.merge.Main",
        "group_id": "com.example.merge.Main:97f8bbd025f5",
        "project_id": "workspace-migration",
        "target_overrides": {
            "target-table": "`databricks-migrate-activity`.schema1.customer_events_dual_clone_1"
        }
    },
    "target-table": "`databricks-migrate-activity`.schema1.customer_events_dual_clone_1",
    "target_table": "`databricks-migrate-activity`.schema1.customer_events_dual_clone_1"
}
MIGRATED_DAG_CONF = {
    "dual_run": {
        "mode": "migrated",
        "clone_index": 2,
        "main_class": "com.example.merge.Main",
        "group_id": "com.example.merge.Main:97f8bbd025f5",
        "project_id": "workspace-migration",
        "target_overrides": {
            "target-table": "databricks-migrate-activity.schema1.customer_events_dual_clone_2"
        }
    },
    "target-table": "databricks-migrate-activity.schema1.customer_events_dual_clone_2",
    "target_table": "databricks-migrate-activity.schema1.customer_events_dual_clone_2"
}


def _serverless_pyspark_task(task_key: str, python_file: str, parameters: list[str] | None = None) -> dict:
    return {
        "run_name": task_key,
        "tasks": [
            {
                "task_key": task_key,
                "environment_key": "default",
                "spark_python_task": {
                    "python_file": python_file,
                    "parameters": parameters or [],
                },
            }
        ],
        "environments": [
            {
                "environment_key": "default",
                "spec": {"environment_version": "4"},
            }
        ],
    }


with DAG(
    dag_id="dual_run_pipeline_test_spark_merge_serverless_dag",
    default_args=default_args,
    description="Dual-run validation for test_spark_merge_serverless_dag (com.example.merge.Main)",
    schedule=None,
    start_date=datetime(2024, 1, 1),
    catchup=False,
    tags=["dual-run", "bh-migrate", "test_spark_merge_serverless_dag"],
) as dag:
    ensure_dualrun_clones = DatabricksSubmitRunOperator(
        task_id="ensure_dualrun_clones",
        databricks_conn_id=DATABRICKS_CONN_ID,
        json=_serverless_pyspark_task("ensure_clones", "dbfs:/Volumes/databricks-migrate-activity/schema1/dualrun/test_spark_merge_serverless_dag/ensure_clones.py"),
    )

    trigger_source_dag = TriggerDagRunOperator(
        task_id="trigger_source_dag",
        trigger_dag_id="test_spark_merge_serverless_dag",
        conf=SOURCE_DAG_CONF,
        wait_for_completion=True,
    )

    trigger_migrated_dag = TriggerDagRunOperator(
        task_id="trigger_migrated_dag",
        trigger_dag_id="migrated_test_spark_merge_serverless_dag",
        conf=MIGRATED_DAG_CONF,
        wait_for_completion=True,
    )

    compare_dualrun_outputs = DatabricksSubmitRunOperator(
        task_id="compare_dualrun_outputs",
        databricks_conn_id=DATABRICKS_CONN_ID,
        json=_serverless_pyspark_task(
            "compare_outputs",
            "dbfs:/Volumes/databricks-migrate-activity/schema1/dualrun/test_spark_merge_serverless_dag/compare_outputs.py",
            ["--results-path", "dbfs:/tmp/dual_run/compare_results.json"],
        ),
    )

    ensure_dualrun_clones >> [trigger_source_dag, trigger_migrated_dag]
    [trigger_source_dag, trigger_migrated_dag] >> compare_dualrun_outputs