# Dual-run comparison (generated by bh-migrate)

compare_results = {}

# Pair customer_events — basic.row_count
compare_results['customer_events:basic.row_count'] = {}
# Compare pair='customer_events' check=basic.row_count
left_count = spark.sql('''SELECT COUNT(*) AS row_count FROM databricks-migrate-activity.schema1.customer_events_dual_clone_1''').first()[0]
right_count = spark.sql('''SELECT COUNT(*) AS row_count FROM databricks-migrate-activity.schema1.customer_events_dual_clone_2''').first()[0]
delta = right_count - left_count
compare_results['customer_events:basic.row_count']['metrics'] = locals().get('metrics', {})

# Pair customer_events — basic.column_count
compare_results['customer_events:basic.column_count'] = {}
# Compare pair='customer_events' check=basic.column_count
left_columns = len(spark.sql('''DESCRIBE TABLE databricks-migrate-activity.schema1.customer_events_dual_clone_1''').collect())
right_columns = len(spark.sql('''DESCRIBE TABLE databricks-migrate-activity.schema1.customer_events_dual_clone_2''').collect())
compare_results['customer_events:basic.column_count']['metrics'] = locals().get('metrics', {})

# Pair customer_events — basic.schema_equality
compare_results['customer_events:basic.schema_equality'] = {}
# Compare pair='customer_events' check=basic.schema_equality
left_schema = spark.sql('''DESCRIBE TABLE databricks-migrate-activity.schema1.customer_events_dual_clone_1''').collect()
right_schema = spark.sql('''DESCRIBE TABLE databricks-migrate-activity.schema1.customer_events_dual_clone_2''').collect()
schema_match = left_schema == right_schema
compare_results['customer_events:basic.schema_equality']['metrics'] = locals().get('metrics', {})

# Pair customer_events — basic.partition_columns
compare_results['customer_events:basic.partition_columns'] = {}
# Compare pair='customer_events' check=basic.partition_columns
left_partitions = spark.sql('''DESCRIBE DETAIL databricks-migrate-activity.schema1.customer_events_dual_clone_1''').select('partitionColumns').first()[0]
right_partitions = spark.sql('''DESCRIBE DETAIL databricks-migrate-activity.schema1.customer_events_dual_clone_2''').select('partitionColumns').first()[0]
compare_results['customer_events:basic.partition_columns']['metrics'] = locals().get('metrics', {})

# Pair customer_events — nulls.count_per_column
compare_results['customer_events:nulls.count_per_column'] = {}
# Compare pair='customer_events' check=nulls.count_per_column
from pyspark.sql import functions as F
left_df = spark.sql('SELECT * FROM databricks-migrate-activity.schema1.customer_events_dual_clone_1')
right_df = spark.sql('SELECT * FROM databricks-migrate-activity.schema1.customer_events_dual_clone_2')
left_nulls = {c: left_df.select(F.sum(F.col(c).isNull().cast('int')).alias(c)).first()[0] for c in left_df.columns}
right_nulls = {c: right_df.select(F.sum(F.col(c).isNull().cast('int')).alias(c)).first()[0] for c in right_df.columns}
compare_results['customer_events:nulls.count_per_column']['metrics'] = locals().get('metrics', {})

# Pair customer_events — nulls.percentage_per_column
compare_results['customer_events:nulls.percentage_per_column'] = {}
# Compare pair='customer_events' check=nulls.percentage_per_column
left_null_pct = {k: v / left_count for k, v in left_nulls.items()}
right_null_pct = {k: v / right_count for k, v in right_nulls.items()}
compare_results['customer_events:nulls.percentage_per_column']['metrics'] = locals().get('metrics', {})

# Pair customer_events — nulls.newly_introduced
compare_results['customer_events:nulls.newly_introduced'] = {}
# Compare pair='customer_events' check=nulls.newly_introduced
newly_introduced_null_columns = [
    c for c in right_nulls
    if right_nulls.get(c, 0) > left_nulls.get(c, 0)
]
compare_results['customer_events:nulls.newly_introduced']['metrics'] = locals().get('metrics', {})

# Pair customer_events — rows.hash_based
compare_results['customer_events:rows.hash_based'] = {}
# Compare pair='customer_events' check=rows.hash_based
left_hashes = spark.sql("SELECT sha2(concat_ws('||', *), 256) AS h, COUNT(*) c FROM databricks-migrate-activity.schema1.customer_events_dual_clone_1 GROUP BY h")
right_hashes = spark.sql("SELECT sha2(concat_ws('||', *), 256) AS h, COUNT(*) c FROM databricks-migrate-activity.schema1.customer_events_dual_clone_2 GROUP BY h")
hash_in_both = left_hashes.join(right_hashes, 'h', 'inner').count()
hash_only_left = left_hashes.join(right_hashes, 'h', 'left_anti').count()
hash_only_right = right_hashes.join(left_hashes, 'h', 'left_anti').count()
hash_count_mismatch = left_hashes.join(right_hashes, ['h', 'c'], 'full_outer').filter('c IS NULL OR l.c != r.c').count() > 0
compare_results['customer_events:rows.hash_based']['metrics'] = locals().get('metrics', {})

# Pair customer_events — delta_ops.metrics
compare_results['customer_events:delta_ops.metrics'] = {}
# Compare pair='customer_events' check=delta_ops.metrics
left_operations = spark.sql('''DESCRIBE HISTORY databricks-migrate-activity.schema1.customer_events_dual_clone_1 LIMIT 100''').collect()
right_operations = spark.sql('''DESCRIBE HISTORY databricks-migrate-activity.schema1.customer_events_dual_clone_2 LIMIT 100''').collect()
# Compare numTargetRowsInserted/Updated/Deleted per operation
inserted_match = ...  # populate at execution
updated_match = ...
deleted_match = ...
compare_results['customer_events:delta_ops.metrics']['metrics'] = locals().get('metrics', {})

# Pair customer_events — delta_version.starting_version
compare_results['customer_events:delta_version.starting_version'] = {}
# Compare pair='customer_events' check=delta_version.starting_version
left_history = spark.sql('''DESCRIBE HISTORY databricks-migrate-activity.schema1.customer_events_dual_clone_1 LIMIT 100''')
right_history = spark.sql('''DESCRIBE HISTORY databricks-migrate-activity.schema1.customer_events_dual_clone_2 LIMIT 100''')
left_start_version, right_start_version = ...  # derive from left_history/right_history at execution
compare_results['customer_events:delta_version.starting_version']['metrics'] = locals().get('metrics', {})

# Pair customer_events — delta_version.ending_version
compare_results['customer_events:delta_version.ending_version'] = {}
# Compare pair='customer_events' check=delta_version.ending_version
left_history = spark.sql('''DESCRIBE HISTORY databricks-migrate-activity.schema1.customer_events_dual_clone_1 LIMIT 100''')
right_history = spark.sql('''DESCRIBE HISTORY databricks-migrate-activity.schema1.customer_events_dual_clone_2 LIMIT 100''')
left_end_version, right_end_version = ...  # derive from left_history/right_history at execution
compare_results['customer_events:delta_version.ending_version']['metrics'] = locals().get('metrics', {})

# Pair customer_events — delta_version.commit_count
compare_results['customer_events:delta_version.commit_count'] = {}
# Compare pair='customer_events' check=delta_version.commit_count
left_history = spark.sql('''DESCRIBE HISTORY databricks-migrate-activity.schema1.customer_events_dual_clone_1 LIMIT 100''')
right_history = spark.sql('''DESCRIBE HISTORY databricks-migrate-activity.schema1.customer_events_dual_clone_2 LIMIT 100''')
left_commits, right_commits = ...  # derive from left_history/right_history at execution
compare_results['customer_events:delta_version.commit_count']['metrics'] = locals().get('metrics', {})

# Pair customer_events — delta_version.commit_sequence
compare_results['customer_events:delta_version.commit_sequence'] = {}
# Compare pair='customer_events' check=delta_version.commit_sequence
left_sequence = [r.operation for r in spark.sql('''DESCRIBE HISTORY databricks-migrate-activity.schema1.customer_events_dual_clone_1 LIMIT 100''').collect()]
right_sequence = [r.operation for r in spark.sql('''DESCRIBE HISTORY databricks-migrate-activity.schema1.customer_events_dual_clone_2 LIMIT 100''').collect()]
sequence_match = left_sequence == right_sequence
compare_results['customer_events:delta_version.commit_sequence']['metrics'] = locals().get('metrics', {})

compare_results['customer_events:distinct.key_columns'] = {'severity': 'BLOCKED', 'message': 'key_columns not provided'}

compare_results['customer_events:distinct.records_on_keys'] = {'severity': 'BLOCKED', 'message': 'key_columns not provided'}

compare_results['customer_events:distinct.numeric_stats'] = {'severity': 'BLOCKED', 'message': 'numeric_columns not provided'}

compare_results['customer_events:distribution.by_partition'] = {'severity': 'BLOCKED', 'message': 'partition_columns not provided'}

compare_results['customer_events:distribution.by_status'] = {'severity': 'BLOCKED', 'message': 'status_column not provided'}

# Persist compare_results (structure only; severity evaluation is future work)
import json
_results_path = 'gs://{{ var.value.dual_run_bucket }}/dual_run/compare_results.json'
try:
    import dbutils  # type: ignore
    dbutils.fs.put(_results_path, json.dumps(compare_results, default=str), overwrite=True)
except Exception:
    with open("/tmp/compare_results.json", "w", encoding="utf-8") as _f:
        json.dump(compare_results, _f, default=str)
