# Dual-run clone setup (generated by bh-migrate)

CREATE SCHEMA IF NOT EXISTS databricks-migrate-activity.schema1

# Resolve storage location for databricks-migrate-activity.schema1.customer_events
source_loc = spark.sql('DESCRIBE DETAIL databricks-migrate-activity.schema1.customer_events').select('location').first()[0]
parent = source_loc.rstrip('/').rsplit('/', 1)[0]
resolved_clone_locations = {
    1: f"{parent}/customer_events_dual_clone_1",
    2: f"{parent}/customer_events_dual_clone_2",
}

# Clone databricks-migrate-activity.schema1.customer_events_dual_clone_1
if not spark.catalog.tableExists("databricks-migrate-activity.schema1.customer_events_dual_clone_1"):
    spark.sql('''CREATE TABLE IF NOT EXISTS databricks-migrate-activity.schema1.customer_events_dual_clone_1
USING DELTA
LOCATION '{resolved_clone_locations[1]}'
DEEP CLONE databricks-migrate-activity.schema1.customer_events''')

# Clone databricks-migrate-activity.schema1.customer_events_dual_clone_2
if not spark.catalog.tableExists("databricks-migrate-activity.schema1.customer_events_dual_clone_2"):
    spark.sql('''CREATE TABLE IF NOT EXISTS databricks-migrate-activity.schema1.customer_events_dual_clone_2
USING DELTA
LOCATION '{resolved_clone_locations[2]}'
DEEP CLONE databricks-migrate-activity.schema1.customer_events''')
